# Generated by Django 5.1 on 2025-03-18 06:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('genre', models.TextField()),
                ('description', models.TextField(null=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('date_published', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
